version: '3.8'

services:
  app:
    build: .
    entrypoint: ["/docker-entrypoint.sh"]
    command: "npm run dev"
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
