type Post {
  id: ID
  title: String!
  body: String!
  imageUrl: String
  label: String
  createdAt: String!
  updatedAt: String!
  publishedAt: String
  slug: String! @unique
  language: String!
  translate: String
  comments: [Comment] @relation
}

type Comment {
  id: ID
  post: Post!
  user: String!
  body: String!
  createdAt: String!
  deletedAt: String
}

type Query {
  allPosts(language: String!): [Post]
  allPostsPublished(language: String!): [Post] @resolver(name: "published_posts", paginated: true)
  findPostBySlug(slug: String!): Post
  findPostBySlugByPublishedAt(slug: String!): Post @resolver(name: "published_post")
  allCommentsByUser: [Post]
}

type Mutation {
  deleteComments(commentIds: [ID!]!): [ID]! @resolver(name: "delete_comments")
}
