type Post {
  id: ID
  title: String!
  body: String!
  slug: String! @unique
  label: String
  createdAt: String!
  updatedAt: String!
  publishedAt: String
  comments: [Comment] @relation
}

type Comment {
  id: ID
  post: Post!
  user: String!
  body: String!
  createdAt: String!
  deletedAt: String
}

type Query {
  allPosts: [Post]
  allPostsPublished: [Post] @resolver(name: "published_posts", paginated: true)
  findPostBySlug(slug: String!): Post
  findPostBySlugByPublishedAt(slug: String!): Post @resolver(name: "published_post")
}

type Mutation {
  deleteComments(commentIds: [ID!]!): [ID]! @resolver(name: "delete_comments")
}
