type Post {
  id: ID
  title: String!
  body: String!
  slug: String!
  label: String
  createdAt: String!
  updatedAt: String!
  publishedAt: String
}

type Query {
  allPosts: [Post]
  findPostBySlug(slug: String!): Post
  createPost(
    title: String!
    body: String!
    slug: String!
    label: String
    createdAt: String!
    updatedAt: String!
    publishedAt: String
  ): Post
  updatePost(
    title: String
    body: String
    slug: String
    label: String
    updatedAt: String!
    publishedAt: String
  ): Post
  deletePost(id: ID!): Post
}
